library(sf)
library(cancensus)
library(tidyverse)
library(geojsonsf)
library(shinyjs)
library(readr)


options(cancensus.api_key = "CensusMapper_2917694b4ae879aca29dd2ce62134969")

# List regions
regions <- list_census_regions('CA16')

# Filter major metro areas
CMAs <- regions$name[regions$level == "CMA" &
                       regions$pop > 900000]

# get geocodes for CMAs
CMA_codes <- regions$region[regions$name %in% CMAs &
                              regions$level == "CMA"]

table <- tibble::tibble("CMA" = CMAs, "GeoID" =  CMA_codes)

# List census vector "col names"
vec <- list_census_vectors("CA16")

# Choose relevant vector names
vec_mother_tongue <- 
  vec$vector[str_detect(vec$details,
                        pattern =
                          "Mother tongue") & 
               vec$type == "Total" & !is.na(vec$vector)]

vec_POB <- vec$vector[str_detect(vec$details,
                                 pattern =
                                   "Selected places of birth") & 
                        vec$type == "Total" & !is.na(vec$vector)]


vec_vis_minor <- vec$vector[str_detect(vec$details,
                                       pattern =  "Visible minority") & 
                              vec$type == "Total" & !is.na(vec$vector)]

vec_ethnic <- vec$vector[str_detect(vec$details,
                                    pattern =  "Ethnic origin") & 
                           vec$type == "Total" & !is.na(vec$vector)]

# Get all relevant data from census 
data_Edmonton <- get_census(dataset='CA16',
                             regions=list(CMA=table$GeoID[table$CMA == "Edmonton"]),
                             vectors = c(vec_vis_minor,vec_POB,
                                         vec_ethnic,vec_mother_tongue),
                             
                             level="CT", use_cache = TRUE, geo_format = "sf")
#####################################################################


# Backup raw data , comment to save backup from runs
#backup_Edm <- data_Edmonton
minor_data_Edm <- data_Edmonton[,c(1:13,15:28)]

# small DAs with no data has NA values, change to 0.
minor_data_Edm[is.na(minor_data_Edm)] <- 0

# clean col names "use each countries name as the 
# col name and shorten total name.
clean_census <- function(x){
  c <- str_split(x, pattern = ": ", simplify = TRUE)[,2]
  return(c)
}


minor_data_Edm[,str_detect(names(st_drop_geometry(minor_data_Edm)),pattern = "Total -")]  <- NULL
t_ind <- which(str_detect(names(st_drop_geometry(minor_data_Edm)),pattern = "Total"))
minor_data_Edm$Total <- st_drop_geometry(minor_data_Edm)[,t_ind]
minor_data_Edm[,t_ind] <- NULL
minor_data_Edm <- rename_with(minor_data_Edm,clean_census, starts_with("V_CA16"))


# make a list of minority names
minor_nm_Edm <- names(st_drop_geometry(
  minor_data_Edm)[,14:ncol(st_drop_geometry(minor_data_Edm))])


# Calculate percentages, remove NA generated by DAs with zero population
percent <- function(x){
  perc <- round(x*100/minor_data_Edm$Population, digits = 2)
  return(perc)
}


minor_data_Edm <- minor_data_Edm %>%
  mutate_at(minor_nm_Edm, percent)

minor_data_Edm[is.na(minor_data_Edm)] <- 0


# save spatial features to H.D.D as shape file, avoid pulling data multiple 
# times, col names will change due to shape file name length and capitalization
# rules.

minor_df_Edm <- st_drop_geometry(minor_data_Edm)

Edm_CT_geom <- st_geometry(minor_data_Edm)

saveRDS(minor_df_Edm, file = "minor_df_Edm.rds")
saveRDS(minor_nm_Edm, file = "minor_nm_Edm.rds")
st_write(Edm_CT_geom,"Edm_CT_geom.shp", append  = FALSE)

##################################################################################


# Backup raw data , quote to save backup from runs
# POB_backup <- POB_data
POB_data_Edm <- data_Edmonton[,c(1:13,30:150)]

# small DAs with no data has NA values, change to 0.
POB_data_Edm[is.na(POB_data_Edm)] <- 0


# split data into immigrants and recent immigrants
POB_data_Edm_recent <- POB_data_Edm %>% select(-c(14:73))


POB_data_Edm <- POB_data_Edm %>% select(-c(74:134))

# clean col names "use each countries name as the
# col name and shorten total name.

POB_data_Edm <- rename_with(POB_data_Edm,clean_census, starts_with("V_CA16"))
t_ind <- which(str_detect(names(st_drop_geometry(POB_data_Edm)),pattern = "Total"))
POB_data_Edm$Total <- st_drop_geometry(POB_data_Edm)[,t_ind]
POB_data_Edm[,t_ind] <- NULL

POB_data_Edm_recent <- rename_with(POB_data_Edm_recent,clean_census, starts_with("V_CA16"))
t_ind <- which(str_detect(names(st_drop_geometry(POB_data_Edm_recent)),pattern = "Total"))
POB_data_Edm_recent$Total <- st_drop_geometry(POB_data_Edm_recent)[,t_ind]
POB_data_Edm_recent[,t_ind] <- NULL

# make a list of country names
con_nm_Edm <- names(st_drop_geometry(
  POB_data_Edm)[,14:ncol(st_drop_geometry(POB_data_Edm))])

con_nm_Edm_recent <- 
  names(st_drop_geometry(
    POB_data_Edm_recent)[,14:ncol(st_drop_geometry(POB_data_Edm_recent))])

# Calculate percentages, remove NA generated by DAs with zero population
percent <- function(x){
  perc <- round(x*100/POB_data_Edm$Population, digits = 2)
  return(perc)
}

POB_data_Edm <- POB_data_Edm %>%
  mutate_at(con_nm_Edm, percent)

POB_data_Edm_recent <- POB_data_Edm_recent %>%
  mutate_at(con_nm_Edm_recent, percent)

POB_data_Edm[is.na(POB_data_Edm)] <- 0
POB_data_Edm_recent[is.na(POB_data_Edm_recent)] <- 0



# remove half of data, the lower half based on mean of pop in CTs
m <- median(max.col(st_drop_geometry(POB_data_Edm)[,con_nm_Edm]))
ind <- names(which(max.col(st_drop_geometry(POB_data_Edm)[,con_nm_Edm]) < m))
POB_data_Edm[,ind] <- NULL

m <- median(max.col(st_drop_geometry(POB_data_Edm_recent)[,con_nm_Edm_recent]))
ind <- names(which(max.col(st_drop_geometry(POB_data_Edm_recent)[,con_nm_Edm_recent]) < m))
POB_data_Edm_recent[,ind] <- NULL

con_nm_Edm <- names(st_drop_geometry(
  POB_data_Edm)[,14:ncol(st_drop_geometry(POB_data_Edm))])

con_nm_Edm_recent <-
  names(st_drop_geometry(
    POB_data_Edm_recent)[,14:ncol(st_drop_geometry(POB_data_Edm_recent))])


# save spatial features to H.D.D as shape file, avoid pulling data multiple 
# times, col names will change due to shape file name length and capitalization
# rules. it is better to save them separately as a data frame, merge later after loading.

POB_df_Edm <- st_drop_geometry(POB_data_Edm)
saveRDS(POB_df_Edm, file = "POB_df_Edm.rds")
saveRDS(con_nm_Edm, file = "con_nm_Edm.rds")

POB_df_Edm_recent <- st_drop_geometry(POB_data_Edm_recent)
saveRDS(POB_df_Edm_recent, file = "POB_df_Edm_rec.rds")
saveRDS(con_nm_Edm_recent, file = "con_nm_Edm_rec.rds")

######################################################################################################################
# get mother tongue data
lang_data_Edm <- data_Edmonton[,c(1:13,429:697)]

# small CTs with no data has NA values, change to 0.
lang_data_Edm[is.na(lang_data_Edm)] <- 0


# clean col names "use each countries name as the
# col name and shorten total name.

lang_data_Edm <- rename_with(lang_data_Edm,clean_census, starts_with("V_CA16"))
t_ind <- which(str_detect(names(st_drop_geometry(lang_data_Edm)),pattern = "Total"))
lang_data_Edm$Total <- st_drop_geometry(lang_data_Edm)[,t_ind]
lang_data_Edm[,t_ind] <- NULL


# make a list of country names
lang_nm_Edm <- names(st_drop_geometry(
  lang_data_Edm)[,16:ncol(st_drop_geometry(lang_data_Edm))])

# Calculate percentages, remove NA generated by DAs with zero population
percent <- function(x){
  perc <- round(x*100/lang_data_Edm$Population, digits = 2)
  return(perc)
}

lang_data_Edm <- lang_data_Edm %>%
  mutate_at(lang_nm_Edm, percent)

lang_data_Edm[is.na(lang_data_Edm)] <- 0


# remove half of data, the lower half based on max percentage of pop in CTs
hist(apply(st_drop_geometry(lang_data_Edm)[,lang_nm_Edm], 2, max), breaks = 100)
summary(apply(st_drop_geometry(lang_data_Edm)[,lang_nm_Edm], 2, max))

m <- median(apply(st_drop_geometry(lang_data_Edm)[,lang_nm_Edm], 2, max))
ind <- names(which(apply(st_drop_geometry(lang_data_Edm)[,lang_nm_Edm], 2, max) < m))
lang_data_Edm[,ind] <- NULL

lang_nm_Edm <- names(st_drop_geometry(
  lang_data_Edm)[,16:ncol(st_drop_geometry(lang_data_Edm))])

# save list and df

lang_df_Edm <- st_drop_geometry(lang_data_Edm)
saveRDS(lang_df_Edm, file = "lang_df_Edm.rds")
saveRDS(lang_nm_Edm, file = "lang_nm_Edm.rds")

######################################################################################################################

# get ethnic data

ethn_data_Edm <- data_Edmonton[,c(1:13,29,151:428)]

# small DAs with no data has NA values, change to 0.
ethn_data_Edm[is.na(ethn_data_Edm)] <- 0


# clean col names "use each countries name as the
# col name and shorten total name.
sum(str_detect(names(ethn_data_Edm), pattern = "Total"))

ethn_data_Edm <- rename_with(ethn_data_Edm,clean_census, starts_with("V_CA16"))
t_ind <- which(str_detect(names(st_drop_geometry(ethn_data_Edm)),pattern = "Total"))
ethn_data_Edm$Total <- st_drop_geometry(ethn_data_Edm)[,t_ind]
ethn_data_Edm[,t_ind] <- NULL


# make a list of country names
ethn_nm_Edm <- names(st_drop_geometry(
  ethn_data_Edm)[,14:ncol(st_drop_geometry(ethn_data_Edm))])

# Calculate percentages, remove NA generated by CTs with zero population
percent <- function(x){
  perc <- round(x*100/ethn_data_Edm$Population, digits = 2)
  return(perc)
}

ethn_data_Edm <- ethn_data_Edm %>%
  mutate_at(ethn_nm_Edm, percent)

ethn_data_Edm[is.na(ethn_data_Edm)] <- 0


# remove half of data, the lower half based on max percentage of pop in CTs
hist(apply(st_drop_geometry(ethn_data_Edm)[,ethn_nm_Edm], 2, max), breaks = 100)
summary(apply(st_drop_geometry(ethn_data_Edm)[,ethn_nm_Edm], 2, max))

m <- median(apply(st_drop_geometry(ethn_data_Edm)[,ethn_nm_Edm], 2, max))
ind <- names(which(apply(st_drop_geometry(ethn_data_Edm)[,ethn_nm_Edm], 2, max) < m))
ethn_data_Edm[,ind] <- NULL

ethn_nm_Edm <- names(st_drop_geometry(
  ethn_data_Edm)[,14:ncol(st_drop_geometry(ethn_data_Edm))])

# save list and df

ethn_df_Edm <- st_drop_geometry(ethn_data_Edm)
saveRDS(ethn_df_Edm, file = "ethn_df_Edm.rds")
saveRDS(ethn_nm_Edm, file = "ethn_nm_Edm.rds")

